# Generated by Django 5.1 on 2024-09-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="mood",
            field=models.UUIDField(),
        ),
    ]
